apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-account
  labels:
    app: bank-account
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      name: bank-account
      labels:
        app: bank-account
        version: v1
    spec:
      containers:
        - name: bank-account
          image: claudioed/bank-account
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
  selector:
    matchLabels:
      app: bank-account
